# Generated by Django 4.2.9 on 2024-01-09 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('COMPUTE', 'Compute'), ('STORAGE', 'Storage'), ('NETWORK', 'Network'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_vendor_name'),
        ),
        migrations.AddField(
            model_name='product',
            name='cloud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clouds.cloud'),
        ),
        migrations.AddField(
            model_name='cloud',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clouds.vendor'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id'], name='id_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['cloud'], name='cloud_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['type'], name='type_idx'),
        ),
    ]
